### ISSUE TITLE
Spelling Mistakes & Inconsistent "Coming Soon" Message

### ISSUE THREAD

**Issue by ibra** [Spu7Nix/spwn_docs#17]
![image](https://user-images.githubusercontent.com/61324615/127016993-5f67585f-83ca-4359-8253-25c69a17b351.png)
![image](https://user-images.githubusercontent.com/61324615/127016996-5c69f10a-788b-49c3-af65-6a8d2b3cb071.png)
![image](https://user-images.githubusercontent.com/61324615/127017006-04f1b6e1-2761-4c08-84bd-5880ef30f0f9.png)

**Comment by Reamuji** [comment]
That not an issue. that a content
