### ISSUE TITLE
Spelling Mistake Found On The Page Detailing Operators

### ISSUE THREAD

**Issue by coltonisgod234** [Spu7Nix/spwn_docs#67]
I was making a project in SPWN and i read over here: [SPWN Operators Page, aka the page i'm talking about](https://spu7nix.net/spwn/#/operators?id=operators)

right here under the `^=` operator i saw `Seta a variable to the power of a value`. i'll attach a screenshot:
![image](https://github.com/Spu7Nix/spwn_docs/assets/141529267/79878b22-ae35-48ee-be47-ff164b56f5a9)

**Comment by SpeckyYT** [comment]
there are like 69420 misspells on the docs lmao

Comig soom

**Comment by lambda-p** [comment]
> there are like 69420 misspells on the docs lmao
> 
> 
> 
> Comig soom

Thank you, I wasn't aware of thet

**Comment by lambda-p** [comment]
I take it this won't get fixed, so I'll close this issue now
